"""Add doctor specialty and online status

Revision ID: f1e766312f50
Revises: 9e63979df1b1
Create Date: 2025-07-01 21:35:14.876462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e766312f50'
down_revision = '9e63979df1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('doctor_user_fk', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('is_online')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint('dk_user_fk', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
