""" add conversation status

Revision ID: f3af5a7bebc3
Revises: ef07ef6dff7d
Create Date: 2025-07-03 02:47:55.575364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3af5a7bebc3'
down_revision = 'ef07ef6dff7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
